# Generated by Django 3.2.10 on 2021-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211212_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blog_post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
